on:
  push:
    branches:
      - deploy/develop
  workflow_dispatch:
  
jobs:
  run_pull:
    name: Deploy and Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Add SSH Key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add host to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H pog.threemusketeer.click >> ~/.ssh/known_hosts
    
    - name: Connect, Pull, and Build Docker
      run: |
        ssh admin@pog.threemusketeer.click << EOF
          set -e
          cd /home/admin/Documents/roomify/roomify-sfu-server
          git stash | true
          git pull origin deploy/develop
          cd /home/admin/Documents/roomify
          echo "${{ secrets.SSH_PASS }}" | sudo -S docker compose up sfu-server --build -d
        EOF