on:
  push:
    branches:
      - deploy/develop
  workflow_dispatch:
  
jobs:
  run_pull:
    name: Deploy and Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Add SSH Key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass
    
    - name: Connect, Pull, and Build Docker
      run: |
        sshpass -p "${{ secrets.SSH_PASS }}" ssh -o StrictHostKeyChecking=no admin@pog.threemusketeer.click << EOF
          set -e
          cd /home/admin/Documents/roomify/roomify-sfu-server
          git stash | true
          git pull origin deploy/develop
          cd /home/admin/Documents/roomify
          echo "${{ secrets.SSH_PASS }}" | sudo -S docker compose up --build -d
        EOF